name: Anuniaq Siberians
favicon: null
layout_spectrum: 0.3897849034983665
typography_spectrum: 0.4237390623893589
title: Anuniaq Siberians
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04706733603961766
  lightness: 0.01092411344870925
  saturation: 0.37218627356924117
  rhythmicContrast: 0.7956244442611933
purpose: []
